name: Run Unit Tests and Lint Files
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main    
jobs: 
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm i
              npm run build
              npm run test:unit
              npm run lint
